name: Python package

on:
  push:
  workflow_dispatch:
    inputs:
      non_integration_tests:
        description: 'Running non-integration tests'
        required: true
        default: true

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          make env
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Running Non-Integration Tests
        if: github.event.inputs.non_integration_tests == true
        run: |
          make tests

      - name: Running Integration Tests
        run: |
          make test_integrations
